# Generated by Django 5.2.7 on 2025-10-24 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("student", "0002_studentcourse_alter_studentprofile_student_course"),
    ]

    operations = [
        migrations.AlterField(
            model_name="studentprofile",
            name="student_course",
            field=models.ManyToManyField(blank=True, to="student.course"),
        ),
        migrations.DeleteModel(
            name="StudentCourse",
        ),
    ]
